### ISSUE TITLE
登入後 重複拜訪 /login 會報錯

### ISSUE THREAD

**Issue by ricksu978** [Game-as-a-Service/Lobby-Platform-Service#112]
## 問題
當使用者登入成功後，再次訪問 /login 會拋出 error

## 期望行為
應該要能夠再次轉導到 Auth0 進行第三方驗證

## 錯誤原因
後端目前會進行 Auth0 第三方驗證的路徑為 `/oauth2/authorization/auth0`。
前端使用登入的路徑為 `/login?type={id}`，需要有個機制將路徑轉導到 `/oauth2/authorization/auth0`。
目前透過 `AuthenticationException` exception handler 處理這部分的轉導。
但如果已經登入成功後就不會進到 `AuthenticationException` 的 exception handler。

## 解決方法
應該將轉導的處理從 exception handler 移出，讓每次請求 `/login` 都會轉導到正確處理的路徑

**Comment by m1a2st** [comment]
我跟Rick有討論出一個解法，提供你作參考
當登入成功後，我們把session清空
在 CustomSuccessHandler新增加
```
request.session.invalidate()
```

**Comment by kuoche1712003** [comment]
@m1a2st @ricksu978 
有點太 hack 的做法
我還是想從源頭解決
解法已經寫在 issue 上了
