### ISSUE TITLE
GET /rooms perPage=20 return empty

### ISSUE THREAD

**Issue by ricksu978** [Game-as-a-Service/Lobby-Platform-Service#143]
- perPage=20 return empty
- perPage=10 return empty
- perPage=2 return empty
- perPage=1 才會有 result

**Comment by m1a2st** [comment]
@ricksu978 應該請前端帶0進來比較好，所以這張單子應該不會改

**Comment by ricksu978** [comment]
已由前端解決
https://github.com/Game-as-a-Service/Game-Lobby-Web/issues/287
