### ISSUE TITLE
Web Socket Test - Player Ready

### ISSUE THREAD

**Issue by ricksu978** [Game-as-a-Service/Lobby-Platform-Service#187]
AC:
- [x] 前端整合測試
- [x] 測是不是只有房間收到
- [x] 訊息格式與 Miro 格式相同

**Comment by m1a2st** [comment]
測試結果：
沒有看到 websocket 的訊息
 ❌前端整合測試
 ❌測是不是只有房間收到
 ❌訊息格式與 Miro 格式相同

**Comment by m1a2st** [comment]
test done

**Comment by ricksu978** [comment]
✅Tested on production
