### ISSUE TITLE
Web Socket Test - Leave Room

### ISSUE THREAD

**Issue by ricksu978** [Game-as-a-Service/Lobby-Platform-Service#188]
AC:
- [x] 前端整合測試
- [x] 與前端 double check 有沒有實作
- [x] 與前端 double check 格式
- [x] 測是不是只有房間收到
- [x] 訊息格式與 Miro 格式相同

**Comment by mikaeloduh** [comment]
local 實測訊息格式：

```
42["USER_LEFT",{"user":{"id":"<TESTID>","nickname":"<TESTNICKNAME>"},"roomId":"<TESTROOMID>"}]	1701612698.9993432
```

是陣列

Miro 上的格式：
https://miro.com/app/board/uXjVMZ2iw5Q=/?moveToWidget=3458764558526668306&cot=14

是 key-value 物件


這樣正確？

**Comment by mikaeloduh** [comment]
翻了下後端的 code

```kt
socketIOServer.broadcastOperations.sendEvent(type.toString(), data)
```

這樣的確會變成 array，問題是前端知道嗎？這樣跟文件也沒有對齊。

**Comment by mikaeloduh** [comment]
沒事了，API 正確。
