### ISSUE TITLE
🐛 Endpoint `/rooms/{roomId}:endgame` must be authorized

### ISSUE THREAD

**Issue by ricksu978** [Game-as-a-Service/Lobby-Platform-Service#202]
# Bug Description
結束遊戲 API `/rooms/{roomId}:endgame` 不需要 JWT Token 就可以關閉任何房間的遊戲。

# Expected Behviour
- 呼叫 Endpoint 一定需要該遊戲房間玩家的 JWT

# Acceptance Criteria
### Given 
- Player "P1" and Player "P2" 正在 Room "R1" 進行遊戲中。
### When
- 用 Player "P2" (or "P1") JWT 呼叫「結束遊戲」API
### Then
- Player "P1" 螢幕關閉遊戲畫面並回到 Room "R1"
- Player "P2" 螢幕關閉遊戲畫面並回到 Room "R1"
- Room "R1" 狀態為 "WAITING"

### Given 
- Player "P1" and Player "P2" 正在 Room "R1" 進行遊戲中 ("PLAYING")。
### When
- 用 Player "P3" JWT 呼叫「結束遊戲」API
### Then
- 「結束遊戲」API 回傳 403
- Player "P1" 遊戲畫面不受影響
- Player "P2" 遊戲畫面不受影響
- Room "R1" 狀態不變 ("PLAYING")

### Given 
- Player "P1" and Player "P2" 正在 Room "R1" 進行遊戲中 ("PLAYING")。
### When
- 不帶 JWT 呼叫「結束遊戲」API
### Then
- 「結束遊戲」API 回傳 401
- Player "P1" 遊戲畫面不受影響
- Player "P2" 遊戲畫面不受影響
- Room "R1" 狀態不變 ("PLAYING")

**Comment by kuoche1712003** [comment]
2. 檢查玩家 API 改回應 400
```json
{
   "timestamp":"2024-03-10T21:10:10.169852",
   "errorCode":"P005",
   "message":"Player(3) is not in the room(R1)."
}
```
