### ISSUE TITLE
搜尋最新註冊的遊戲

### ISSUE THREAD

**Issue by ricksu978** [Game-as-a-Service/Lobby-Platform-Service#214]
## Acceptance Criteria
- 遊戲的 API Endpoint 可以搜尋最新註冊的遊戲 (依照「註冊日期」排序，由新到舊)

## Tasks
- [x] 設計 API Route, Request and Response (可以 re-use 現有的 endpoint 或 新的 endpoint)
- [ ] 實作他!

**Comment by kuoche1712003** [comment]
目前查詢遊戲的 api 是以下的 api
`GET /games`
```json
[
    {
        "id": "6496cff366371525c35a04c5",
        "name": "明星3缺1麻將",
        "img": "https://placekitten.com/300/300",
        "minPlayers": 4,
        "maxPlayers": 4,
        "createdOn": "2024-01-01T14:00:00Z"
    }
]
```
預計調整為可接受 query parameter
`GET /games?sort_by=createdOn`
response body 結構不變
這樣就會以 createdOn 排序由新到舊

之後要實作其他的也可以用這個 query parameter 傳遞不同的值
決定如何排序
